#!/bin/bash

# ENV VARIABLE
SINGPERA_USER="singpera"
SINGPERA_HOME_DIR="/home/$SINGPERA_USER"
SINGPERA_SSH_DIR="$SINGPERA_HOME_DIR/.ssh"
SINGPERA_SSH_KEY="$SINGPERA_SSH_DIR/singpera_key"
DEFAULT_STORAGE_FILE="$SINGPERA_HOME_DIR/.singpera_storage"

# HELPER FUNCTIONS
log(){
	echo "[INFO] $1" >&2
}

warning(){
	echo "[WARNING] $1" >&2
}

error(){
	echo "[ERROR] $1" >&2
}

installIfMissing(){
	log "checking dependencies..."
	for packages in "$@"; do
		if ! command -v $packages &> /dev/null; then
			log "$packages not found. installing..."
			apt update && apt install $packages -y
		else
			log "$packages already installed."
		fi
	done

}

ensureSingperaUser(){
	if id $SINGPERA_USER &> /dev/null; then
		log "singpera system user already exists."
	else
		log "creating singpera system user: $SINGPERA_USER"
		useradd \
			--system \
			--create-home \
			--home-dir "$SINGPERA_HOME_DIR" \
			--shell /bin/bash \
			--comment "singpera system user" \
			"$SINGPERA_USER"
		log "singpera system user has been successfully created!"
	fi

	if [ ! -d "$SINGPERA_SSH_DIR" ]; then
		log "creating singpera ssh credential directory..."
		mkdir -p "$SINGPERA_SSH_DIR"
		chmod 700 "$SINGPERA_SSH_DIR"
		chown -R "$SINGPERA_USER":"$SINGPERA_USER" "$SINGPERA_SSH_DIR"
		log "finished creating singpera ssh credential directory."
	fi
}

setupSSHKey(){
	if [ -f "$SINGPERA_SSH_KEY" ]; then
		log "singpera ssh key pair already exists."
	else
		log "creating singpera ssh key pair..."
		sudo -u "$SINGPERA_USER" ssh-keygen -t rsa -b 2048 -f "$SINGPERA_SSH_KEY" -N ""
		log "finished creating singpera ssh key pair."
	fi
}

setupDefaultStorage(){
	read -p "Enter storage server (user@host): " STORAGE
	echo "$STORAGE" | sudo tee "$DEFAULT_STORAGE_FILE" > /dev/null
	chown -R "$SINGPERA_USER":"$SINGPERA_USER" "$DEFAULT_STORAGE_FILE"
	log "default storage saved."
	echo "$STORAGE"
}

copySSHKey(){
	local STORAGE=$1
	log "copying public key to remote storage ($STORAGE)"
	sudo -u "$SINGPERA_USER" ssh-copy-id -i "$SINGPERA_SSH_KEY.pub" "$STORAGE"
}

setupRemoteStorageDir(){
	local STORAGE=$1
	read -p "Enter path on storage server for singpera backups [default: ~/singpera]: " REMOTE_DIR
	REMOTE_DIR="${REMOTE_DIR:-~/singpera}"

	log "creating singpera directory on $STORAGE at $REMOTE_DIR..."

	sudo -u "$SINGPERA_USER" ssh -i "$SINGPERA_SSH_KEY" "$STORAGE" "
		if ! command -v rsync &> /dev/null; then
			echo 'installing rsync on storage server...'
			apt update && apt install rsync -y
			echo 'finished installing rsync.'
		else
			echo 'rynsc already installed on storage server.'
		fi

		mkdir -p $REMOTE_DIR && \
		chmod 750 $REMOTE_DIR && \
		echo 'finished creating singpera directory on $REMOTE_DIR.'
	"

	if [ $? -eq 0 ]; then
		echo "$REMOTE_DIR" | sudo tee "$SINGPERA_HOME_DIR/.singpera_remote_dir" > /dev/null
		chown "$SINGPERA_USER:$SINGPERA_USER" "$SINGPERA_HOME_DIR/.singpera_remote_dir"
		log "remote singpera directory configured: $STORAGE:$REMOTE_DIR"
	else
		error "failed to configure singpera remote directory. please check ssh connection."
	fi
}

getStorage(){
	if sudo test -f "$DEFAULT_STORAGE_FILE"; then
		STORAGE=$(sudo cat "$DEFAULT_STORAGE_FILE")
		read -p "use default storage? ($STORAGE) [y/n]: " CHOICE >&2
		if [[ "$CHOICE" == "y" ]]; then
			echo "$STORAGE"
			return
		fi
	fi
	read -p "enter storage server (user@host): " STORAGE
	echo "$STORAGE"
}

getRemoteDir(){
	if sudo test -f "$SINGPERA_HOME_DIR/.singpera_remote_dir"; then
		DEFAULT_REMOTE_DIR=$(sudo cat "$SINGPERA_HOME_DIR/.singpera_remote_dir")
		read -p "enter destination path on storage server [default: $DEFAULT_REMOTE_DIR]: " DEST
		echo "${DEST:-$DEFAULT_REMOTE_DIR}"
	else
		read -p "enter destination path on the storage server: " DEST
		echo "$DEST"
	fi
}

showHelp(){
	echo "=== SINGPERA CLI HELP ==="
	echo "Penggunaan:"
	echo "  1. Mode Interaktif (Menu):"
	echo "     singpera"
	echo ""
	echo "  2. One-shot Backup Otomatis:"
	echo "     singpera <SRC> <DEST>"
	echo "     Contoh: singpera /home/user/data user@192.168.1.50:/backup"
	echo ""
	echo "  3. Scheduled Backup Otomatis:"
	echo "     singpera -c \"CRON_TIME\" <SRC> <DEST>"
	echo "     Contoh: singpera -c \"0 2 * * *\" /home/user/data user@192.168.1.50:/backup"
	echo ""
	echo "Opsi:"
	echo "  -h          Menampilkan pesan bantuan ini"
	echo "  -c          Menentukan jadwal cron untuk backup terjadwal"
}

# MAIN FUNCTIONS
configureSingpera(){
	log "===configuring singpera...==="

	if [ "$EUID" -ne 0 ]; then
		error "gunakan superuser untuk dapat mengkonfigurasi singpera! (gunakan sudo)"
		return 1
	fi

	#installing dependencies
	installIfMissing rsync cron ssh sshpass

	#ensuring singpera service user exists
	ensureSingperaUser

	#initializing singpera ssh key pair
	setupSSHKey

	#initializing singpera remote storage
	STORAGE=$(setupDefaultStorage)

	#copying public ssh key to remote storage
	copySSHKey "$STORAGE"

	#initializing singpera remote storage directory
	setupRemoteStorageDir "$STORAGE"

	log "configuration done!"
	log "singpera ssh public key:"
	cat "$SINGPERA_SSH_KEY.pub"
}

scheduledBackup(){
	log "===creating a backup schedule...==="
	read -p "enter full path of the source file to backup: " SRC
	STORAGE=$(getStorage)
	DEST=$(getRemoteDir)

	read -p "Enter cron schedule (e.g. 0 2 * * *): " CRON_TIME

	CMD="/usr/bin/rsync -avz -e 'ssh -i $SINGPERA_SSH_KEY' --rsync-path='rsync' $SRC $STORAGE:$DEST"
	(sudo crontab -u root -l 2>/dev/null; echo "$CRON_TIME $CMD") \
	| sudo crontab -u root -

	log "Scheduled backup created."
}

oneshotBackup(){
	log "===one shot backup==="
	read -p "enter source path to backup: " SRC
	STORAGE=$(getStorage)
	DEST=$(getRemoteDir)

	log "running one shot backup..."
	sudo -u root rsync -avz -e "ssh -i $SINGPERA_SSH_KEY" --rsync-path="rsync" "$SRC" "$STORAGE:$DEST"
	log "backup completed."
}


CRON_TIME=""

#RUN INTERACTIVE MODE IF NO ARGUMENTS NOR OPTIONS PASSED
if [ $# -eq 0 ]; then
	while true; do
		echo ""
		echo "WELCOME TO SINGPERA"
		echo "==================="
		echo "1. configure singpera"
		echo "2. schedule a backup"
		echo "3. oneshot backup"
		echo "4. show help"
		echo "5. exit"
		echo "==================="
		echo ""
		read -p "Choose option: " option
		case $option in
			1) configureSingpera;;
			2) scheduledBackup;;
			3) oneshotBackup;;
			4) showHelp;;
			5) exit 0;;
			*) echo "Invalid option";;
		esac
	done
else
#READ PASSED OPTIONS
	while getopts "hc:" flag; do
		case "$flag" in
			h)
				showHelp
				exit 0
				;;
			c)
				CRON_TIME="$OPTARG"
				;;
			*)
				showHelp
				exit 1
				;;
		esac
	done

	shift $((OPTIND - 1))

	SRC="$1"
	DEST_RAW="$2"
#SOURCE AND DESTINATION ARGUMENT VALIDATION
	if [ -z "$SRC" ] || [ -z "$DEST_RAW" ]; then
		error "Argumen SRC (Source) dan DEST (Destination) wajib diisi!"
		echo ""
		showHelp
		exit 1
	fi
#FEEDING STORAGE AND DEST VARIABLE
	if [[ "$DEST_RAW" == *":"* ]]; then
		STORAGE="${DEST_RAW%%:*}"
		DEST="${DEST_RAW#*:}"
	else
		error "Format DEST salah! Gunakan format 'user@host:/path/tujuan'"
		exit 1
	fi
#SCHEDULE A BACKUP IF -C OPTION IS PASSED
	if [ -n "$CRON_TIME" ]; then
		log "=== Menjalankan CLI Scheduled Backup ==="
		log "Source      : $SRC"
		log "Storage     : $STORAGE"
		log "Destination : $DEST"
		log "Cron Time   : $CRON_TIME"

		CMD="/usr/bin/rsync -avz -e 'ssh -i $SINGPERA_SSH_KEY' --rsync-path='rsync' $SRC $STORAGE:$DEST"
		(sudo crontab -u root -l 2>/dev/null; echo "$CRON_TIME $CMD") \
		| sudo crontab -u root -

		log "Scheduled backup successfully created via CLI."
		exit 0
	else
#RUN A BACKUP IF NO -C OPTION IS PASSED
		log "=== Menjalankan CLI One-shot Backup ==="
		log "Source      : $SRC"
		log "Storage     : $STORAGE"
		log "Destination : $DEST"

		log "running one shot backup..."
		sudo -u root rsync -avz -e "ssh -i $SINGPERA_SSH_KEY" --rsync-path="rsync" "$SRC" "$STORAGE:$DEST"
		log "backup completed."
		exit 0
	fi
fi
